version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
  database:
    container_name: database
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: doctorwho3210
      POSTGRES_USER: postgres
      POSTGRES_DB: voting_sections
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "host=database user=postgres password=doctorwho3210 dbname=voting_sections port=5432"
      PORT: 5000
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgresql://postgres:doctorwho3210@database:5432/voting_sections
      GOOSE_MIGRATION_DIR: ./migrations
      GOOSE_TABLE: public.migrations
    depends_on:
      - database
    command: sh -c "goose up && go run . "

volumes:  
  pgdata: {}