version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
  database:
    container_name: database
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: doctorwho3210
      POSTGRES_USER: postgres
      POSTGRES_DB: voting_sections
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend
    image: francescoxx/go-app:1.0.0
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    command: go run .

volumes:  
  pgdata: {}